version: '3'

services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_URL=${DATABASE_URL}
      # - POSTGRES_PASSWORD=${DATABASE_PASS}
      # - POSTGRES_DB=${DATABASE_DB}
      # - DATABASE_HOST=${DATABASE_HOST}
    # build: ./database/migration
    ports:
      - "5432:5432"

    volumes:
      - ./database/migration/docker-db.sql:/docker-entrypoint-initdb.d/docker-db.sql
      - postgresdb:./database/migration
    entrypoint: "heroku pg:psql postgresql-globular-60369 --app gowalletx -f /app/database/migration/docker-db.sql"
  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "afns@alura.com"
  #     PGADMIN_DEFAULT_PASSWORD: "123456"
  #   ports:
  #     - "54321:80"
  #   depends_on:
  #     - postgres

volumes:
  postgresdb:
