version: '3'

services:
  # api:
  #   container_name: gowallet
  #   build:
  #     context: .
  #     dockerfile: DockerFile
  #   ports: 
  #     - 8000:8000
  #   environment:
  #     - PORT: 8000
  #     - DATABASE_URL: postgres 
  #   depends_on:
      # - postgres
  
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_DB}
      - DATABASE_HOST=${DATABASE_HOST}
    build: ./database/migration
    ports:
      - "5432:5432"

    volumes:
      - ./database/migration/docker-db.sql:/docker-entrypoint-initdb.d/docker-db.sql
      - postgresdb:/var/lib/postgresql/data
  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "afns@alura.com"
  #     PGADMIN_DEFAULT_PASSWORD: "123456"
  #   ports:
  #     - "54321:80"
  #   depends_on:
  #     - postgres
volumes:
  postgresdb:
